# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sparql_endpoint: http://almere.pilod.nl/sparql
    query_path     : "%kernel.root_dir%/../var/sparql"

    cache:
        adapter:
            name: filesystem
            options:
                cache_dir      : "%kernel.root_dir%/../var/cache/%kernel.environment%/app"
                dir_permission : '0760'
                file_permission: '0660'

services:
    sparql_client:
        class    : EasyRdf\Sparql\Client
        arguments: ["%sparql_endpoint%"]

    zend_cache:
        class    : Zend\Cache\Storage\StorageInterface
        factory  : [Zend\Cache\StorageFactory, factory]
        arguments: ["%cache%"]

    app.dao.kb:
        class    : AppBundle\Dao\Kb
        arguments: ["@sparql_client", "%query_path%", "@zend_cache"]
