# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sparql_endpoint: http://almere.pilod.nl/sparql
    query_path     : "%kernel.root_dir%/../var/sparql"

services:
    sparql_client:
        class    : EasyRdf\Sparql\Client
        arguments: ["%sparql_endpoint%"]
